### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by agate**
Hi @ainsleyc 

I made some adjustments for this package.
- made a better exception handling in the lib
- added test cases
- improved the README.md

I don't know if you can see this pull request. If you can see it. Can you make a review and approve it? And I don't have permission to upload the npm package onto https://www.npmjs.com. So please consider  upgrade the version in package.json and make a upload.

Thanks,
Hao.

### CODE REVIEW

**Comment by ainsleyc** [comment]
Ah cool. Thanks!

**Comment by agate** [comment]
Hi @ainsleyc can you also push a new npm package :laughing: Thank you!

**Comment by ainsleyc** [comment]
Ah, will do, thanks for the reminder =)

**Comment by ainsleyc** [comment]
Done.

**Comment by agate** [comment]
:+1: Thank you!

**Pull request merged**
